name: EAS Build

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release tag to attach the .apk file"
        required: true

jobs:
  build:
    name: Install, Build, and Upload
    runs-on: ubuntu-latest
    environment: AoiCrypto
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ vars.EXPO_TOKEN }}

      - name: Download build artifact
        working-directory: ./Frontend
        run: |
          APK_URL=$(eas build:list --platform android --status finished --limit 1 --json --non-interactive | jq -r '.[0].artifacts.applicationArchiveUrl')
          if [ -z "$APK_URL" ]; then
            echo "No finished builds found. Exiting."
            exit 1
          fi
          APK_NAME="AoiCrypto_${{ github.event.inputs.release_tag }}.apk"
          curl -v -o "$APK_NAME" "$APK_URL"
          
      - name: Log APK URL
        run: echo "APK_URL=$APK_URL"

      - name: Verify Downloaded File
        run: |
          file "$APK_NAME"
          cat "$APK_NAME"

      - name: Validate APK
        run: |
          ls -lh "$APK_NAME"
          sha256sum "$APK_NAME"

      - name: Create or Update GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./Frontend/AoiCrypto_${{ github.event.inputs.release_tag }}.apk
          tag_name: ${{ github.event.inputs.release_tag }}
          prerelease: false
          body: "Release built with EAS and attached APK."
